// Premier League Manager — 2025-26 season squads
// Team IDs: arsenal, astonvilla, bournemouth, brentford, brighton, burnley,
//           chelsea, crystalpalace, everton, fulham, leeds, liverpool,
//           mancity, manunited, newcastle, nforest, sunderland, tottenham,
//           westham, wolves
// (Luton and Sheffield United are NOT in 2025-26; promoted teams are
//  Leeds, Burnley, Sunderland; relegated from 2024-25 were Leicester,
//  Ipswich, Southampton.)

const PLM_SQUADS = {
    arsenal: [
        { name: 'David Raya',           pos: 'GK',  rating: 86 },
        { name: 'Kepa Arrizabalaga',    pos: 'GK',  rating: 76 },
        { name: 'Karl Hein',            pos: 'GK',  rating: 64 },
        { name: 'William Saliba',       pos: 'DEF', rating: 88 },
        { name: 'Gabriel Magalhaes',    pos: 'DEF', rating: 86 },
        { name: 'Ben White',            pos: 'DEF', rating: 82 },
        { name: 'Jurrien Timber',       pos: 'DEF', rating: 82 },
        { name: 'Riccardo Calafiori',   pos: 'DEF', rating: 80 },
        { name: 'Myles Lewis-Skelly',   pos: 'DEF', rating: 78 },
        { name: 'Cristhian Mosquera',   pos: 'DEF', rating: 76 },
        { name: 'Declan Rice',          pos: 'MID', rating: 88 },
        { name: 'Martin Zubimendi',     pos: 'MID', rating: 84 },
        { name: 'Martin Odegaard',      pos: 'MID', rating: 87 },
        { name: 'Bukayo Saka',          pos: 'MID', rating: 89 },
        { name: 'Gabriel Martinelli',   pos: 'MID', rating: 83 },
        { name: 'Ethan Nwaneri',        pos: 'MID', rating: 77 },
        { name: 'Christian Norgaard',   pos: 'MID', rating: 76 },
        { name: 'Viktor Gyokeres',      pos: 'FWD', rating: 86 },
        { name: 'Kai Havertz',          pos: 'FWD', rating: 83 },
        { name: 'Leandro Trossard',     pos: 'FWD', rating: 80 },
    ],
    astonvilla: [
        { name: 'Emiliano Martinez',    pos: 'GK',  rating: 85 },
        { name: 'Marco Bizot',          pos: 'GK',  rating: 72 },
        { name: 'Robin Olsen',          pos: 'GK',  rating: 66 },
        { name: 'Matty Cash',           pos: 'DEF', rating: 77 },
        { name: 'Ezri Konsa',           pos: 'DEF', rating: 81 },
        { name: 'Pau Torres',           pos: 'DEF', rating: 80 },
        { name: 'Tyrone Mings',         pos: 'DEF', rating: 76 },
        { name: 'Ian Maatsen',          pos: 'DEF', rating: 75 },
        { name: 'Lucas Digne',          pos: 'DEF', rating: 74 },
        { name: 'Youri Tielemans',      pos: 'MID', rating: 80 },
        { name: 'Boubacar Kamara',      pos: 'MID', rating: 78 },
        { name: 'John McGinn',          pos: 'MID', rating: 78 },
        { name: 'Morgan Rogers',        pos: 'MID', rating: 80 },
        { name: 'Amadou Onana',         pos: 'MID', rating: 78 },
        { name: 'Leon Bailey',          pos: 'MID', rating: 75 },
        { name: 'Ollie Watkins',        pos: 'FWD', rating: 84 },
        { name: 'Donyell Malen',        pos: 'FWD', rating: 75 },
        { name: 'Jadon Sancho',         pos: 'FWD', rating: 74 },
    ],
    bournemouth: [
        { name: 'Djordje Petrovic',     pos: 'GK',  rating: 76 },
        { name: 'Mark Travers',         pos: 'GK',  rating: 68 },
        { name: 'Will Dennis',          pos: 'GK',  rating: 60 },
        { name: 'Adrien Truffert',      pos: 'DEF', rating: 75 },
        { name: 'Marcos Senesi',        pos: 'DEF', rating: 78 },
        { name: 'Bafode Diakite',       pos: 'DEF', rating: 76 },
        { name: 'Julio Soler',          pos: 'DEF', rating: 68 },
        { name: 'James Hill',           pos: 'DEF', rating: 70 },
        { name: 'Veljko Milosavljevic', pos: 'DEF', rating: 66 },
        { name: 'Ryan Christie',        pos: 'MID', rating: 75 },
        { name: 'Lewis Cook',           pos: 'MID', rating: 75 },
        { name: 'Tyler Adams',          pos: 'MID', rating: 74 },
        { name: 'Alex Scott',           pos: 'MID', rating: 73 },
        { name: 'Marcus Tavernier',     pos: 'MID', rating: 74 },
        { name: 'Justin Kluivert',      pos: 'MID', rating: 77 },
        { name: 'David Brooks',         pos: 'MID', rating: 72 },
        { name: 'Evanilson',            pos: 'FWD', rating: 76 },
        { name: 'Eli Junior Kroupi',    pos: 'FWD', rating: 70 },
        { name: 'Ben Doak',             pos: 'FWD', rating: 72 },
    ],
    brentford: [
        { name: 'Caoimhin Kelleher',    pos: 'GK',  rating: 78 },
        { name: 'Hakon Valdimarsson',   pos: 'GK',  rating: 68 },
        { name: 'Ellery Balcombe',      pos: 'GK',  rating: 60 },
        { name: 'Nathan Collins',       pos: 'DEF', rating: 78 },
        { name: 'Ethan Pinnock',        pos: 'DEF', rating: 76 },
        { name: 'Sepp van den Berg',    pos: 'DEF', rating: 74 },
        { name: 'Aaron Hickey',         pos: 'DEF', rating: 73 },
        { name: 'Keane Lewis-Potter',   pos: 'DEF', rating: 73 },
        { name: 'Michael Kayode',       pos: 'DEF', rating: 72 },
        { name: 'Rico Henry',           pos: 'DEF', rating: 73 },
        { name: 'Mikkel Damsgaard',     pos: 'MID', rating: 76 },
        { name: 'Yehor Yarmoliuk',      pos: 'MID', rating: 73 },
        { name: 'Mathias Jensen',       pos: 'MID', rating: 75 },
        { name: 'Jordan Henderson',     pos: 'MID', rating: 74 },
        { name: 'Kevin Schade',         pos: 'MID', rating: 74 },
        { name: 'Dango Ouattara',       pos: 'MID', rating: 73 },
        { name: 'Igor Thiago',          pos: 'FWD', rating: 75 },
        { name: 'Reiss Nelson',         pos: 'FWD', rating: 72 },
    ],
    brighton: [
        { name: 'Bart Verbruggen',      pos: 'GK',  rating: 80 },
        { name: 'Jason Steele',         pos: 'GK',  rating: 68 },
        { name: 'Tom McGill',           pos: 'GK',  rating: 62 },
        { name: 'Lewis Dunk',           pos: 'DEF', rating: 79 },
        { name: 'Jan Paul van Hecke',   pos: 'DEF', rating: 78 },
        { name: 'Joel Veltman',         pos: 'DEF', rating: 75 },
        { name: 'Pervis Estupinan',     pos: 'DEF', rating: 77 },
        { name: 'Ferdi Kadioglu',       pos: 'DEF', rating: 76 },
        { name: 'Adam Webster',         pos: 'DEF', rating: 73 },
        { name: 'Diego Gomez',          pos: 'MID', rating: 74 },
        { name: 'Mats Wieffer',         pos: 'MID', rating: 74 },
        { name: 'Yasin Ayari',          pos: 'MID', rating: 73 },
        { name: 'Carlos Baleba',        pos: 'MID', rating: 80 },
        { name: 'Kaoru Mitoma',         pos: 'MID', rating: 82 },
        { name: 'Yankuba Minteh',       pos: 'MID', rating: 76 },
        { name: 'Georginio Rutter',     pos: 'MID', rating: 77 },
        { name: 'Danny Welbeck',        pos: 'FWD', rating: 77 },
        { name: 'Joao Pedro',           pos: 'FWD', rating: 78 },
        { name: 'Evan Ferguson',        pos: 'FWD', rating: 74 },
    ],
    burnley: [
        { name: 'Martin Dubravka',      pos: 'GK',  rating: 74 },
        { name: 'Max Weiss',            pos: 'GK',  rating: 66 },
        { name: 'Etienne Green',        pos: 'GK',  rating: 60 },
        { name: 'Kyle Walker',          pos: 'DEF', rating: 78 },
        { name: 'Maxime Esteve',        pos: 'DEF', rating: 72 },
        { name: 'Hjalmar Ekdal',        pos: 'DEF', rating: 69 },
        { name: 'Axel Tuanzebe',        pos: 'DEF', rating: 67 },
        { name: 'Quilindschy Hartman',  pos: 'DEF', rating: 68 },
        { name: 'Connor Roberts',       pos: 'DEF', rating: 68 },
        { name: 'Lesley Ugochukwu',     pos: 'MID', rating: 72 },
        { name: 'Josh Cullen',          pos: 'MID', rating: 70 },
        { name: 'Florentino Luis',      pos: 'MID', rating: 71 },
        { name: 'Jacob Bruun Larsen',   pos: 'MID', rating: 69 },
        { name: 'Loum Tchaouna',        pos: 'MID', rating: 69 },
        { name: 'Jaidon Anthony',       pos: 'MID', rating: 68 },
        { name: 'Zian Flemming',        pos: 'FWD', rating: 70 },
        { name: 'Lyle Foster',          pos: 'FWD', rating: 69 },
        { name: 'Armando Broja',        pos: 'FWD', rating: 69 },
    ],
    chelsea: [
        { name: 'Robert Sanchez',       pos: 'GK',  rating: 78 },
        { name: 'Filip Jorgensen',      pos: 'GK',  rating: 74 },
        { name: 'Mike Penders',         pos: 'GK',  rating: 66 },
        { name: 'Levi Colwill',         pos: 'DEF', rating: 81 },
        { name: 'Wesley Fofana',        pos: 'DEF', rating: 79 },
        { name: 'Benoit Badiashile',    pos: 'DEF', rating: 76 },
        { name: 'Trevoh Chalobah',      pos: 'DEF', rating: 76 },
        { name: 'Marc Cucurella',       pos: 'DEF', rating: 80 },
        { name: 'Reece James',          pos: 'DEF', rating: 82 },
        { name: 'Malo Gusto',           pos: 'DEF', rating: 77 },
        { name: 'Moises Caicedo',       pos: 'MID', rating: 84 },
        { name: 'Enzo Fernandez',       pos: 'MID', rating: 83 },
        { name: 'Romeo Lavia',          pos: 'MID', rating: 76 },
        { name: 'Dario Essugo',         pos: 'MID', rating: 72 },
        { name: 'Cole Palmer',          pos: 'MID', rating: 88 },
        { name: 'Pedro Neto',           pos: 'MID', rating: 80 },
        { name: 'Jamie Gittens',        pos: 'MID', rating: 76 },
        { name: 'Estevao Willian',      pos: 'MID', rating: 77 },
        { name: 'Liam Delap',           pos: 'FWD', rating: 76 },
        { name: 'Nicolas Jackson',      pos: 'FWD', rating: 77 },
        { name: 'Joao Pedro',           pos: 'FWD', rating: 76 },
    ],
    crystalpalace: [
        { name: 'Dean Henderson',       pos: 'GK',  rating: 80 },
        { name: 'Walter Benitez',       pos: 'GK',  rating: 72 },
        { name: 'Remi Matthews',        pos: 'GK',  rating: 62 },
        { name: 'Marc Guehi',           pos: 'DEF', rating: 82 },
        { name: 'Maxence Lacroix',      pos: 'DEF', rating: 77 },
        { name: 'Chris Richards',       pos: 'DEF', rating: 76 },
        { name: 'Daniel Munoz',         pos: 'DEF', rating: 77 },
        { name: 'Tyrick Mitchell',      pos: 'DEF', rating: 74 },
        { name: 'Borna Sosa',           pos: 'DEF', rating: 72 },
        { name: 'Jaydee Canvot',        pos: 'DEF', rating: 68 },
        { name: 'Adam Wharton',         pos: 'MID', rating: 79 },
        { name: 'Daichi Kamada',        pos: 'MID', rating: 75 },
        { name: 'Cheick Doucoure',      pos: 'MID', rating: 75 },
        { name: 'Will Hughes',          pos: 'MID', rating: 72 },
        { name: 'Ismaila Sarr',         pos: 'MID', rating: 76 },
        { name: 'Yeremy Pino',          pos: 'MID', rating: 74 },
        { name: 'Jean-Philippe Mateta', pos: 'FWD', rating: 80 },
        { name: 'Eddie Nketiah',        pos: 'FWD', rating: 74 },
        { name: 'Christantus Uche',     pos: 'FWD', rating: 70 },
    ],
    everton: [
        { name: 'Jordan Pickford',      pos: 'GK',  rating: 82 },
        { name: 'Mark Travers',         pos: 'GK',  rating: 68 },
        { name: 'Joao Virginia',        pos: 'GK',  rating: 64 },
        { name: 'James Tarkowski',      pos: 'DEF', rating: 78 },
        { name: 'Jarrad Branthwaite',   pos: 'DEF', rating: 81 },
        { name: 'Michael Keane',        pos: 'DEF', rating: 72 },
        { name: 'Vitalii Mykolenko',    pos: 'DEF', rating: 75 },
        { name: 'Nathan Patterson',     pos: 'DEF', rating: 71 },
        { name: 'Jake O\'Brien',        pos: 'DEF', rating: 72 },
        { name: 'Ashley Young',         pos: 'DEF', rating: 68 },
        { name: 'Idrissa Gueye',        pos: 'MID', rating: 74 },
        { name: 'James Garner',         pos: 'MID', rating: 73 },
        { name: 'Merlin Rohl',          pos: 'MID', rating: 73 },
        { name: 'Iliman Ndiaye',        pos: 'MID', rating: 76 },
        { name: 'Jack Grealish',        pos: 'MID', rating: 80 },
        { name: 'Dwight McNeil',        pos: 'MID', rating: 74 },
        { name: 'Beto',                 pos: 'FWD', rating: 73 },
        { name: 'Thierno Barry',        pos: 'FWD', rating: 70 },
    ],
    fulham: [
        { name: 'Bernd Leno',           pos: 'GK',  rating: 80 },
        { name: 'Benjamin Lecomte',     pos: 'GK',  rating: 70 },
        { name: 'Steven Benda',         pos: 'GK',  rating: 62 },
        { name: 'Calvin Bassey',        pos: 'DEF', rating: 77 },
        { name: 'Joachim Andersen',     pos: 'DEF', rating: 78 },
        { name: 'Issa Diop',            pos: 'DEF', rating: 72 },
        { name: 'Antonee Robinson',     pos: 'DEF', rating: 79 },
        { name: 'Kenny Tete',           pos: 'DEF', rating: 75 },
        { name: 'Timothy Castagne',     pos: 'DEF', rating: 74 },
        { name: 'Ryan Sessegnon',       pos: 'DEF', rating: 71 },
        { name: 'Sasa Lukic',           pos: 'MID', rating: 74 },
        { name: 'Sander Berge',         pos: 'MID', rating: 75 },
        { name: 'Tom Cairney',          pos: 'MID', rating: 72 },
        { name: 'Harry Wilson',         pos: 'MID', rating: 74 },
        { name: 'Andreas Pereira',      pos: 'MID', rating: 75 },
        { name: 'Alex Iwobi',           pos: 'MID', rating: 76 },
        { name: 'Raul Jimenez',         pos: 'FWD', rating: 76 },
        { name: 'Rodrigo Muniz',        pos: 'FWD', rating: 75 },
        { name: 'Adama Traore',         pos: 'FWD', rating: 73 },
    ],
    leeds: [
        { name: 'Lucas Perri',          pos: 'GK',  rating: 74 },
        { name: 'Karl Darlow',          pos: 'GK',  rating: 66 },
        { name: 'Alex Cairns',          pos: 'GK',  rating: 60 },
        { name: 'Pascal Struijk',       pos: 'DEF', rating: 74 },
        { name: 'Joe Rodon',            pos: 'DEF', rating: 72 },
        { name: 'Jayden Bogle',         pos: 'DEF', rating: 70 },
        { name: 'Gabriel Gudmundsson',  pos: 'DEF', rating: 70 },
        { name: 'Jaka Bijol',           pos: 'DEF', rating: 72 },
        { name: 'Sam Byram',            pos: 'DEF', rating: 66 },
        { name: 'Ethan Ampadu',         pos: 'MID', rating: 74 },
        { name: 'Anton Stach',          pos: 'MID', rating: 72 },
        { name: 'Ao Tanaka',            pos: 'MID', rating: 70 },
        { name: 'Brenden Aaronson',     pos: 'MID', rating: 71 },
        { name: 'Sean Longstaff',       pos: 'MID', rating: 70 },
        { name: 'Daniel James',         pos: 'MID', rating: 70 },
        { name: 'Wilfried Gnonto',      pos: 'MID', rating: 72 },
        { name: 'Lukas Nmecha',         pos: 'FWD', rating: 69 },
        { name: 'Dominic Calvert-Lewin',pos: 'FWD', rating: 71 },
        { name: 'Noah Okafor',          pos: 'FWD', rating: 70 },
    ],
    liverpool: [
        { name: 'Alisson Becker',       pos: 'GK',  rating: 88 },
        { name: 'Giorgi Mamardashvili', pos: 'GK',  rating: 78 },
        { name: 'Armin Pecsi',          pos: 'GK',  rating: 64 },
        { name: 'Virgil van Dijk',      pos: 'DEF', rating: 89 },
        { name: 'Ibrahima Konate',      pos: 'DEF', rating: 83 },
        { name: 'Jarell Quansah',       pos: 'DEF', rating: 76 },
        { name: 'Joe Gomez',            pos: 'DEF', rating: 78 },
        { name: 'Milos Kerkez',         pos: 'DEF', rating: 80 },
        { name: 'Andrew Robertson',     pos: 'DEF', rating: 82 },
        { name: 'Jeremie Frimpong',     pos: 'DEF', rating: 81 },
        { name: 'Conor Bradley',        pos: 'DEF', rating: 77 },
        { name: 'Alexis Mac Allister',  pos: 'MID', rating: 86 },
        { name: 'Ryan Gravenberch',     pos: 'MID', rating: 83 },
        { name: 'Dominik Szoboszlai',   pos: 'MID', rating: 84 },
        { name: 'Curtis Jones',         pos: 'MID', rating: 78 },
        { name: 'Florian Wirtz',        pos: 'MID', rating: 87 },
        { name: 'Mohamed Salah',        pos: 'FWD', rating: 91 },
        { name: 'Alexander Isak',       pos: 'FWD', rating: 88 },
        { name: 'Hugo Ekitike',         pos: 'FWD', rating: 82 },
        { name: 'Cody Gakpo',           pos: 'FWD', rating: 83 },
    ],
    mancity: [
        { name: 'Gianluigi Donnarumma', pos: 'GK',  rating: 88 },
        { name: 'James Trafford',       pos: 'GK',  rating: 74 },
        { name: 'Marcus Bettinelli',    pos: 'GK',  rating: 64 },
        { name: 'Ruben Dias',           pos: 'DEF', rating: 88 },
        { name: 'Josko Gvardiol',       pos: 'DEF', rating: 85 },
        { name: 'Nathan Ake',           pos: 'DEF', rating: 81 },
        { name: 'John Stones',          pos: 'DEF', rating: 82 },
        { name: 'Rayan Ait-Nouri',      pos: 'DEF', rating: 80 },
        { name: 'Matheus Nunes',        pos: 'DEF', rating: 77 },
        { name: 'Vitor Reis',           pos: 'DEF', rating: 74 },
        { name: 'Rodri',                pos: 'MID', rating: 90 },
        { name: 'Bernardo Silva',       pos: 'MID', rating: 86 },
        { name: 'Phil Foden',           pos: 'MID', rating: 88 },
        { name: 'Mateo Kovacic',        pos: 'MID', rating: 82 },
        { name: 'Tijjani Reijnders',    pos: 'MID', rating: 83 },
        { name: 'Rayan Cherki',         pos: 'MID', rating: 80 },
        { name: 'Jeremy Doku',          pos: 'MID', rating: 82 },
        { name: 'Savinho',              pos: 'MID', rating: 80 },
        { name: 'Erling Haaland',       pos: 'FWD', rating: 93 },
        { name: 'Omar Marmoush',        pos: 'FWD', rating: 82 },
    ],
    manunited: [
        { name: 'Andre Onana',          pos: 'GK',  rating: 80 },
        { name: 'Senne Lammens',        pos: 'GK',  rating: 74 },
        { name: 'Altay Bayindir',       pos: 'GK',  rating: 70 },
        { name: 'Harry Maguire',        pos: 'DEF', rating: 78 },
        { name: 'Lisandro Martinez',    pos: 'DEF', rating: 82 },
        { name: 'Matthijs de Ligt',     pos: 'DEF', rating: 82 },
        { name: 'Leny Yoro',            pos: 'DEF', rating: 79 },
        { name: 'Luke Shaw',            pos: 'DEF', rating: 79 },
        { name: 'Diogo Dalot',          pos: 'DEF', rating: 79 },
        { name: 'Noussair Mazraoui',    pos: 'DEF', rating: 78 },
        { name: 'Patrick Dorgu',        pos: 'DEF', rating: 74 },
        { name: 'Bruno Fernandes',      pos: 'MID', rating: 87 },
        { name: 'Casemiro',             pos: 'MID', rating: 80 },
        { name: 'Manuel Ugarte',        pos: 'MID', rating: 77 },
        { name: 'Kobbie Mainoo',        pos: 'MID', rating: 79 },
        { name: 'Amad Diallo',          pos: 'MID', rating: 81 },
        { name: 'Mason Mount',          pos: 'MID', rating: 77 },
        { name: 'Matheus Cunha',        pos: 'FWD', rating: 82 },
        { name: 'Bryan Mbeumo',         pos: 'FWD', rating: 82 },
        { name: 'Benjamin Sesko',       pos: 'FWD', rating: 82 },
        { name: 'Joshua Zirkzee',       pos: 'FWD', rating: 75 },
    ],
    newcastle: [
        { name: 'Nick Pope',            pos: 'GK',  rating: 82 },
        { name: 'Aaron Ramsdale',       pos: 'GK',  rating: 77 },
        { name: 'John Ruddy',           pos: 'GK',  rating: 62 },
        { name: 'Sven Botman',          pos: 'DEF', rating: 80 },
        { name: 'Fabian Schar',         pos: 'DEF', rating: 80 },
        { name: 'Dan Burn',             pos: 'DEF', rating: 76 },
        { name: 'Malick Thiaw',         pos: 'DEF', rating: 78 },
        { name: 'Kieran Trippier',      pos: 'DEF', rating: 78 },
        { name: 'Tino Livramento',      pos: 'DEF', rating: 78 },
        { name: 'Lewis Hall',           pos: 'DEF', rating: 75 },
        { name: 'Bruno Guimaraes',      pos: 'MID', rating: 86 },
        { name: 'Sandro Tonali',        pos: 'MID', rating: 83 },
        { name: 'Joelinton',            pos: 'MID', rating: 80 },
        { name: 'Joe Willock',          pos: 'MID', rating: 74 },
        { name: 'Jacob Ramsey',         pos: 'MID', rating: 75 },
        { name: 'Harvey Barnes',        pos: 'MID', rating: 77 },
        { name: 'Anthony Gordon',       pos: 'FWD', rating: 83 },
        { name: 'Anthony Elanga',       pos: 'FWD', rating: 78 },
        { name: 'Nick Woltemade',       pos: 'FWD', rating: 78 },
        { name: 'Yoane Wissa',          pos: 'FWD', rating: 77 },
    ],
    nforest: [
        { name: 'Matz Sels',            pos: 'GK',  rating: 78 },
        { name: 'Carlos Miguel',        pos: 'GK',  rating: 68 },
        { name: 'John Victor',          pos: 'GK',  rating: 62 },
        { name: 'Murillo',              pos: 'DEF', rating: 82 },
        { name: 'Nikola Milenkovic',    pos: 'DEF', rating: 78 },
        { name: 'Morato',               pos: 'DEF', rating: 72 },
        { name: 'Neco Williams',        pos: 'DEF', rating: 73 },
        { name: 'Ola Aina',             pos: 'DEF', rating: 74 },
        { name: 'Alex Moreno',          pos: 'DEF', rating: 72 },
        { name: 'Nicolo Savona',        pos: 'DEF', rating: 71 },
        { name: 'Elliot Anderson',      pos: 'MID', rating: 78 },
        { name: 'Ryan Yates',           pos: 'MID', rating: 72 },
        { name: 'Douglas Luiz',         pos: 'MID', rating: 78 },
        { name: 'Morgan Gibbs-White',   pos: 'MID', rating: 82 },
        { name: 'Callum Hudson-Odoi',   pos: 'MID', rating: 76 },
        { name: 'Dan Ndoye',            pos: 'MID', rating: 76 },
        { name: 'Chris Wood',           pos: 'FWD', rating: 79 },
        { name: 'Igor Jesus',           pos: 'FWD', rating: 72 },
        { name: 'Arnaud Kalimuendo',    pos: 'FWD', rating: 73 },
    ],
    sunderland: [
        { name: 'Robin Roefs',          pos: 'GK',  rating: 70 },
        { name: 'Anthony Patterson',    pos: 'GK',  rating: 68 },
        { name: 'Simon Moore',          pos: 'GK',  rating: 60 },
        { name: 'Nordi Mukiele',        pos: 'DEF', rating: 76 },
        { name: 'Dan Ballard',          pos: 'DEF', rating: 70 },
        { name: 'Omar Alderete',        pos: 'DEF', rating: 70 },
        { name: 'Arthur Masuaku',       pos: 'DEF', rating: 68 },
        { name: 'Trai Hume',            pos: 'DEF', rating: 68 },
        { name: 'Reinildo Mandava',     pos: 'DEF', rating: 70 },
        { name: 'Granit Xhaka',         pos: 'MID', rating: 78 },
        { name: 'Habib Diarra',         pos: 'MID', rating: 72 },
        { name: 'Enzo Le Fee',          pos: 'MID', rating: 72 },
        { name: 'Noah Sadiki',          pos: 'MID', rating: 69 },
        { name: 'Simon Adingra',        pos: 'MID', rating: 73 },
        { name: 'Chemsdine Talbi',      pos: 'MID', rating: 68 },
        { name: 'Wilson Isidor',        pos: 'FWD', rating: 72 },
        { name: 'Brian Brobbey',        pos: 'FWD', rating: 72 },
        { name: 'Eliezer Mayenda',      pos: 'FWD', rating: 68 },
    ],
    tottenham: [
        { name: 'Guglielmo Vicario',    pos: 'GK',  rating: 82 },
        { name: 'Antonin Kinsky',       pos: 'GK',  rating: 72 },
        { name: 'Brandon Austin',       pos: 'GK',  rating: 62 },
        { name: 'Cristian Romero',      pos: 'DEF', rating: 84 },
        { name: 'Micky van de Ven',     pos: 'DEF', rating: 82 },
        { name: 'Radu Dragusin',        pos: 'DEF', rating: 75 },
        { name: 'Destiny Udogie',       pos: 'DEF', rating: 79 },
        { name: 'Pedro Porro',          pos: 'DEF', rating: 80 },
        { name: 'Djed Spence',          pos: 'DEF', rating: 74 },
        { name: 'Kevin Danso',          pos: 'DEF', rating: 74 },
        { name: 'James Maddison',       pos: 'MID', rating: 82 },
        { name: 'Joao Palhinha',        pos: 'MID', rating: 82 },
        { name: 'Rodrigo Bentancur',    pos: 'MID', rating: 78 },
        { name: 'Yves Bissouma',        pos: 'MID', rating: 76 },
        { name: 'Archie Gray',          pos: 'MID', rating: 75 },
        { name: 'Mohammed Kudus',       pos: 'MID', rating: 81 },
        { name: 'Xavi Simons',          pos: 'MID', rating: 82 },
        { name: 'Dominic Solanke',      pos: 'FWD', rating: 80 },
        { name: 'Richarlison',          pos: 'FWD', rating: 78 },
        { name: 'Brennan Johnson',      pos: 'FWD', rating: 76 },
    ],
    westham: [
        { name: 'Alphonse Areola',      pos: 'GK',  rating: 78 },
        { name: 'Mads Hermansen',       pos: 'GK',  rating: 74 },
        { name: 'Wes Foderingham',      pos: 'GK',  rating: 64 },
        { name: 'Max Kilman',           pos: 'DEF', rating: 78 },
        { name: 'Konstantinos Mavropanos', pos: 'DEF', rating: 74 },
        { name: 'Jean-Clair Todibo',    pos: 'DEF', rating: 76 },
        { name: 'Aaron Wan-Bissaka',    pos: 'DEF', rating: 76 },
        { name: 'Emerson Palmieri',     pos: 'DEF', rating: 73 },
        { name: 'El Hadji Malick Diouf',pos: 'DEF', rating: 72 },
        { name: 'Oliver Scarles',       pos: 'DEF', rating: 69 },
        { name: 'Edson Alvarez',        pos: 'MID', rating: 78 },
        { name: 'Tomas Soucek',         pos: 'MID', rating: 77 },
        { name: 'Lucas Paqueta',        pos: 'MID', rating: 80 },
        { name: 'Guido Rodriguez',      pos: 'MID', rating: 73 },
        { name: 'Jarrod Bowen',         pos: 'MID', rating: 82 },
        { name: 'Mateus Fernandes',     pos: 'MID', rating: 73 },
        { name: 'Crysencio Summerville',pos: 'MID', rating: 75 },
        { name: 'Niclas Fullkrug',      pos: 'FWD', rating: 76 },
        { name: 'Callum Wilson',        pos: 'FWD', rating: 74 },
    ],
    wolves: [
        { name: 'Jose Sa',              pos: 'GK',  rating: 78 },
        { name: 'Sam Johnstone',        pos: 'GK',  rating: 74 },
        { name: 'Daniel Bentley',       pos: 'GK',  rating: 62 },
        { name: 'Toti Gomes',           pos: 'DEF', rating: 74 },
        { name: 'Yerson Mosquera',      pos: 'DEF', rating: 72 },
        { name: 'Santiago Bueno',       pos: 'DEF', rating: 72 },
        { name: 'Emmanuel Agbadou',     pos: 'DEF', rating: 72 },
        { name: 'Nelson Semedo',        pos: 'DEF', rating: 74 },
        { name: 'Hugo Bueno',           pos: 'DEF', rating: 68 },
        { name: 'Ladislav Krejci',      pos: 'DEF', rating: 73 },
        { name: 'Joao Gomes',           pos: 'MID', rating: 78 },
        { name: 'Andre',                pos: 'MID', rating: 75 },
        { name: 'Jean-Ricner Bellegarde', pos: 'MID', rating: 72 },
        { name: 'Tommy Doyle',          pos: 'MID', rating: 70 },
        { name: 'Marshall Munetsi',     pos: 'MID', rating: 70 },
        { name: 'Hwang Hee-chan',       pos: 'MID', rating: 72 },
        { name: 'Rodrigo Gomes',        pos: 'MID', rating: 70 },
        { name: 'Jorgen Strand Larsen', pos: 'FWD', rating: 76 },
        { name: 'Fer Lopez',            pos: 'FWD', rating: 70 },
    ],
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = PLM_SQUADS;
}
